### ISSUE TITLE
Multi-Level

### ISSUE THREAD

**Issue by jcldavid** [Jontyy/PHP-Basic-MVC-Framework#2]
Hi, there's something wrong with the request class. If for example my URL is http://localhost/test/framework:

```
private '_controller' => string 'test' (length=3)
private '_method' => string 'framework' (length=3)
private '_args' => 
```

where framework is the folder where all the framework's file are.

**Comment by Jontyy** [comment]
HI @Apathetic012 

Tthe routing with this is very limited, for example as you noted it needs to be in web root, also you cannot put controller files into sub folders etc.

Really the idea of this was to show what components are needed at a basic level and it is not intended to be used in production.

**Comment by jcldavid** [comment]
That's the problem, I really can't find a good router for a personal MVC that can be used for production. I hope you could help.

**Comment by rudiedirkx** [comment]
How about https://github.com/rudiedirkx/Rudie-on-wheels/blob/master/example_app/config/controllers.php ? You can make levels, use subfolders, link directly to Controllers (the last) or have them auto resolve (the rest).

**Comment by lgt** [comment]
Hi, 

I have been starting to learn the mvc paradigm with your example and I'm finding it really good. What I would like is to extend the request. Could you give me a tip how should I start it?

**Comment by rudiedirkx** [comment]
Extend the request? What do you mean? The routing should be (?) obvious from [controllers.php](https://github.com/rudiedirkx/Rudie-on-wheels/blob/master/example_app/config/) and [routes.php](https://github.com/rudiedirkx/Rudie-on-wheels/blob/master/example_app/config/routes.php).

**Comment by lgt** [comment]
Yes I mean the routing. Actually what Jontyy from scratch has been building up it's a good starting point,  but as  Apathetic012 mentioned is not functional for larger projects.

**Comment by rudiedirkx** [comment]
Right. So what do you want to know about ROW's routing? Pretty much everything is covered in the example_app...

**Comment by Jontyy** [comment]
@lgt To be honest with you I would just create a new file within the application dir ( since its not gonna get updated )

Create a new class and make sure it extends the original request.

Then modify [index.php line 19 ](https://github.com/Jontyy/PHP-Basic-MVC-Framework/blob/master/index.php#L19) and pass a new instance of your custom request to the router.

**Comment by lgt** [comment]
thanks a lot for your advice!

**Comment by Jontyy** [comment]
@lgt by the way if you are going to use this live I would consider adding some security e.g. CSRF and XSS protection

**Comment by lgt** [comment]
okay I will keep in mind and thanks again
