### ISSUE TITLE
What vulnerabilities are possible?

### ISSUE THREAD

**Issue by brightproject** [Jontyy/PHP-Basic-MVC-Framework#5]

**Comment by Jontyy** [comment]
To be honest I've not touched this code for 2-3 years now so no idea.
I know that there is nothing built in for the most common security concerns, e.g. there is nothing to handle XSS, there is no model implementation so potentially could be security issues in the model layer, nothing for CSRF.

I would really not use this for production, it was just done to show how some of the patterns fit together.
